import React from "react";
import type { NonDeletedExcalidrawElement } from "@excalidraw/element/types";
import type { EditorInterface } from "@excalidraw/common";
import type { ActionManager } from "../actions/manager";
import type { AppClassProperties, AppProps, AppState, ExcalidrawProps, UIAppState } from "../types";
import type { JSX } from "react";
type TrayMenuProps = {
    appState: UIAppState;
    actionManager: ActionManager;
    renderJSONExportDialog: () => React.ReactNode;
    renderImageExportDialog: () => React.ReactNode;
    setAppState: React.Component<any, AppState>["setState"];
    elements: readonly NonDeletedExcalidrawElement[];
    onLockToggle: () => void;
    onHandToolToggle: () => void;
    onPenModeToggle: AppClassProperties["togglePenMode"];
    renderTopRightUI?: (isMobile: boolean, appState: UIAppState) => JSX.Element | null;
    renderCustomStats?: ExcalidrawProps["renderCustomStats"];
    renderSidebars: () => JSX.Element | null;
    editorInterface: EditorInterface;
    renderWelcomeScreen: boolean;
    UIOptions: AppProps["UIOptions"];
    app: AppClassProperties;
};
export declare const TrayMenu: ({ appState, elements, actionManager, setAppState, onLockToggle, onHandToolToggle, onPenModeToggle, renderTopRightUI, renderCustomStats, renderSidebars, editorInterface, renderWelcomeScreen, UIOptions, app, }: TrayMenuProps) => import("react/jsx-runtime").JSX.Element;
export {};
